### ISSUE TITLE
[BUG]: ArgumentError in ConceptsController#show 

### ISSUE THREAD

**Issue by mgbeyer** [innoq/iqvoc#348]
The following problem occurs in version 4.9.0 with SKOS-XL functionality under the following circumstances (but I think it has nothing to do with the XL functionality in particular):
- Define a concept mapping (any type) for a given concept
- Save and publish the new version
- Then edit it again, delete the concept mapping formerly added
- Save and publish this new version, too
- A ReverseMatchJob will be written to the underlying database (table "delayed_jobs") stating the mapping is scheduled for removal at the remote site.

Now if you shut down the iQvoc instance and re-start the server and try to navigate to the concept mentioned above, the following error message will be displayed (the problem only occurs after the application has been re-started):
##### undefined class/module ReverseMatchJob

Here's the following (lengthy) stack trace:

```
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/class_loader.rb:53:in `path2class'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/class_loader.rb:53:in `resolve'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/class_loader.rb:45:in `find'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/class_loader.rb:27:in `load'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:360:in `resolve_class'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:165:in `visit_Psych_Nodes_Mapping'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:276:in `visit_Psych_Nodes_Document'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych/nodes/node.rb:37:in `to_ruby'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/psych.rb:246:in `load'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/bundler/gems/iqvoc-4-9-0-extlib-2ac6333c4a05/app/controllers/concepts_controller.rb:49:in `block (3 levels) in show'
C:in `map'
C:in `map'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/bundler/gems/iqvoc-4-9-0-extlib-2ac6333c4a05/app/controllers/concepts_controller.rb:48:in `block (2 levels) in show'
actionpack (4.2.1) lib/action_controller/metal/mime_responds.rb:215:in `call'
actionpack (4.2.1) lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/bundler/gems/iqvoc-4-9-0-extlib-2ac6333c4a05/app/controllers/concepts_controller.rb:41:in `show'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
apipie-rails (0.3.4) lib/apipie/static_dispatcher.rb:65:in `call'
apipie-rails (0.3.4) lib/apipie/extractor/recorder.rb:132:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
rack (1.6.1) lib/rack/content_length.rb:15:in `call'
rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

The trouble spot seems to be in "/app/controllers/concepts_controller.rb" around line # 49 (where the content of the "handler" field is read for the job(s) in a loop and is then given to YAML.load as an argument). Maybe you could shed some light on it?

**Comment by mjansing** [comment]
Looks like a weird auto loading bug. Should be fixed with 6e2fdfdebc558f30e0d566ecb857cdf684cb153c and 4949f7e71b5e25e068242a1fbd4fdcaa231f39e7.
