### ISSUE TITLE
Cannot run iQvoc built from Dockerfile - no nokogiri or mini_portile

### ISSUE THREAD

**Issue by EwaSniegowskaPCSS** [innoq/iqvoc#449]
Hi.
I build the newest codebase using the provided Dockerfile. When I run the app from docker-compose I get an error:

```
iqvoc-web-1  | /usr/local/bundle/gems/bundler-2.4.6/lib/bundler/definition.rb:524:in `materialize':
Could not find nokogiri-1.14.1, mini_portile2-2.8.1 in locally installed gems (Bundler::GemNotFound)
```

I tried adding
```
RUN bundle lock --add-platform x86_64-linux
```
into Dockerfile, following: https://stackoverflow.com/questions/66308227/could-not-find-nokogiri-1-11-1-in-any-of-the-sources-while-deploying-a-heroku-ap
but the result is the same.

Can you reproduce this error?
I used the following code version: https://github.com/innoq/iqvoc/commit/d453a4462953b790057fc2edd95c303ff25305d4
but the problem persists since few commits.

**Comment by EwaSniegowskaPCSS** [comment]
I updated the Dockerfile with newer Ruby version:
`
FROM ruby:2.7
`

but I'm getting another runtime error:

```
iqvoc-web-1  | /bundle/ruby/2.7.0/gems/delayed_job-4.1.10/lib/delayed/command.rb:5:in `rescue in <main>':
You need to add gem 'daemons' to your Gemfile if you wish to use it. (RuntimeError)`
